name: Mirror to Personal Repo for Deployment

on:
    push:
        branches:
            - main

jobs:
    mirror:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Debug Secret Access
              run: |
                  echo "The token is: ${{ secrets.PERSONAL_ACCESS_TOKEN }}"

            - name: Push to personal repo
              run: |
                  git remote add personal https://purelyKai:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/purelyKai/AdviseU-Frontend-Web-Mirror.git
                  git push personal --all
